import {
	BackgroundColor,
	BorderTopWidth,
	BorderTopStyle,
	BorderTopColor,
	BorderRightWidth,
	BorderRightStyle,
	BorderRightColor,
	BorderBottomWidth,
	BorderBottomStyle,
	BorderBottomColor,
	BorderLeftWidth,
	BorderLeftStyle,
	BorderLeftColor,
	PaddingTop,
	PaddingRight,
	PaddingBottom,
	PaddingLeft,
	MarginTop,
	MarginRight,
	MarginBottom,
	MarginLeft,
	Height,
	Width
} from './content';

export * from './content';

export default {
	BackgroundColor,
	BorderTopWidth,
	BorderTopStyle,
	BorderTopColor,
	BorderRightWidth,
	BorderRightStyle,
	BorderRightColor,
	BorderBottomWidth,
	BorderBottomStyle,
	BorderBottomColor,
	BorderLeftWidth,
	BorderLeftStyle,
	BorderLeftColor,
	PaddingTop,
	PaddingRight,
	PaddingBottom,
	PaddingLeft,
	MarginTop,
	MarginRight,
	MarginBottom,
	MarginLeft,
	Height,
	Width
};
